# Generated by Django 4.2.2 on 2023-08-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="show_description",
            new_name="short_description",
        ),
    ]
